### PR TITLE
Fix stalled connections where SSL buffer is not full

### LINKED ISSUE #44: transfer closed with 16467 bytes remaining to read
We use mod_zip with nginx 1.6.3 serving zip files with HTTPS (openssl 1.0.1k).

For a list of 3 files, we can reproduce an error where the client does not receive the full zip archive but experiences a timeout with the error above as not all data announced in "Content-Length" is sent by the server.

The response body (as generated by a rails application is)
````
a6f0fd29 28763 /data/X/200%20NM/200%20NM.xml 200 NM/200 NM.xml
c43dfa28 1386 /data/X/Media/foo.png Media/foo.png
32b4e3ce 1203 /data/X/66C9EB32CB5F4A1B95F3CA1D6BE0C5B4.png 66C9EB32CB5F4A1B95F3CA1D6BE0C5B4.png
````
The response header is (curl output)
````
< Date: Thu, 09 Apr 2015 22:51:43 GMT
< Content-Type: application/zip
< Content-Length: 31904
< Connection: keep-alive
< Status: 200 OK
< Content-Disposition: attachment; filename=bulletin-1428619903-7729.zip
````
The transfer is stalled after 15437 bytes.

The most strange thing is that the size of the second file matters (the 1386 bytes) but not the content. If we reorder the body lines for mod_zip to have "Media/foo.png" at the end, it works without any issues. 

When we change the size of the file (by adding random bytes), it works again. When the file size (random data) is between 1285 and 1386 bytes, the transfer is always stalled.

The error log of nginx (even with debugging enabled) does not show errors but in turn complains about the client having timed out (after 60 seconds, the keep-alive timeout) with "client timed out (110: Connection timed out) while sending response to client"

So both client and server seem to wait for each other and then timeout.

### PR DESCRIPTION
**Pull request by Dragoonwings**
May be this can tottaly fix #44

### CODE REVIEW

File: ngx_http_zip_module.c [hunk 1]
```diff
@@ -609,7 +609,7 @@ ngx_http_zip_send_piece(ngx_http_request_t *r, ngx_http_zip_ctx_t *ctx,
         rc = ngx_http_zip_send_trailer_piece(r, ctx, piece, req_range);
     } else if (piece->type == zip_central_directory_piece) {
         rc = ngx_http_zip_send_central_directory_piece(r, ctx, piece, req_range);
-    }
+    }
```
Comment (evanmiller) [inline ngx_http_zip_module.c:612]: Please remove

Comment (Dragoonwings) [reply ngx_http_zip_module.c]: Deleted, sorry for that

**Comment by evanmiller** [comment]
Thanks for the contribution and explanation in the attached ticket. Let's try it.
